name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        check-latest: true

    - name: build
      run: go build -o win-mac-addr.exe main.go

    - name: generate release note
      run: |
        go install github.com/git-chglog/git-chglog/cmd/git-chglog
        git-chglog -c .github/chglog/release.yml $(git describe --tags) > RELEASE.md

    - name: publish release
      uses: softprops/action-gh-release@v1
      with:
        files: win-mac-addr.exe
        body_path: RELEASE.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
