name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v5
      with:
        go-version: '1.20'
        check-latest: true

    - name: build artifacts
      run: go build -o win-mac-addr.exe main.go

    - name: build changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        commitMode: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: publish release
      uses: softprops/action-gh-release@v1
      with:
        files: win-mac-addr.exe
        body: ${{steps.github_release.outputs.changelog}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
